### ISSUE TITLE
error python 3.6.5

### ISSUE THREAD

**Issue by broka78** [mzollin/qr-pirate#53]
Is your software not working on python 3.6.5? Can you fix this? as I did not try it did not work ... it does not start qr2key.py would really like to try your software at work. thanks waiting for an answer

**Comment by mzollin** [comment]
Yes, the most current version is not yet working on python 3 because of some dependencies. As I wrote in the readme, you can use the "stable"-python3 branch that works fine, except it doesn't automatically check the balance of the wallets found.
If you want the automatic balance checking you'll have to use the master branch with python 2
